### ISSUE TITLE
Messages do not send TO discord FROM revolt

### ISSUE THREAD

**Issue by Shadowevil015** [ashisbored/disrev#2]
```
E 2022-03-08 20:29:29,293 asyncio: Task exception was never retrieved
future: <Task finished name='Task-373' coro=<WebsocketHandler.handle_event() done, defined at /home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/websocket.py:70> exception=KeyError('01FTCAT4ACDYTK8XMBNK19P0ZH')>
Traceback (most recent call last):
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/websocket.py", line 79, in handle_event
    await func(payload)
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/websocket.py", line 103, in handle_message
    message = self.state.add_message(cast(MessagePayload, payload))
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/state.py", line 73, in add_message
    message = Message(payload, self)
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/message.py", line 56, in __init__
    author = state.get_member(self.server.id, data["author"])
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/state.py", line 42, in get_member
    return server.get_member(member_id)
  File "/home/shadow/.cache/pypoetry/virtualenvs/disrev-tJJuphXi-py3.10/lib/python3.10/site-packages/revolt/server.py", line 86, in get_member
    return self._members[member_id]

```

Hey there, 

I am using single-channel mode, and the .env is configured correctly, but for some reason, only my messages are sent FROM revolt TO discord, whereas if another person tries to, their message will not be sent on discord, but messages from discord to revolt will be sent, no matter who sends them. 

My suspicion is that this has something to do with me being the bot owner on Revolt, but I also can't code in Python, nor am I a regular user of Revolt.

I hope you have the time to look into this at some point, 

Thanks

 (If you need anymore info, message me on Discord: ShadowEvil015#8887)

**Comment by vague-advice** [comment]
I had the same issue, and i managed to fix it! here is the thing i did:

1: from your ```.json``` file, remove the ```canary.``` (or ```ptb.```) from the webhook url, check to see if your channel ids are correct,

2: profit
